### ISSUE TITLE
Updated R package

### ISSUE THREAD

**Issue by BECollymore** [michael-cw/SurveySolutionsAPI#7]
Hi Michael,
Will we be getting an updated package? This one is excellent and all it needs is to incorporate Workspaces.

Kind regards.

**Comment by michael-cw** [comment]
Hi Burt,

Thank you very much. Yes, it will be updated, I am almost through and now at final testing.

This will be only a partial update for now, and will not contain any of the new graphql functions. I had been focused for too long on fixing the graphql part, but that will still take, and given the user demand (which is very much appreciated), I finally decided to go without it.

I hope its out by end of this week.

Best

Michael

From: Burt Collymore ***@***.***>
Sent: Tuesday, January 25, 2022 9:24 PM
To: michael-cw/SurveySolutionsAPI ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [michael-cw/SurveySolutionsAPI] Updated R package (Issue #7)

[External]

Hi Michael,
Will we be getting an updated package? This one is excellent and all it needs is to incorporate Workspaces.

Kind regards.

-

**Comment by BECollymore** [comment]
Hi Michael,
Thank you so much. This is wonderful news. Yes, trust me, I have been struggling with using other API packages and I am truly appreciative of how intuitive, robust, and complete your R package is, the data export feature is amazing,  I was up and running in no time. Thanks for this amazing tool. Yes, I too had a lot of difficulty with graphql, I never got it to work in the .net package and I’m still researching it, so I feel you there. Anyway, I’m wishing you all the best as I eagerly anticipate the updated release. Here is a link to what your innovation has made possible. Truly appreciated.

https://1drv.ms/v/s!AvlHmpjY7vUQiL8f0gd2Xaoj2EPkRw?e=YEJH4L <https://1drv.ms/v/s!AvlHmpjY7vUQiL8f0gd2Xaoj2EPkRw?e=YEJH4L>

Kind regards,
Burt Collymore

**Comment by BECollymore** [comment]
Hi Michael,
I am writing you with the knowledge of the management of the Central Statistical Office of St.Lucia.  We are at the cusp of rolling out our P&H Census and there are plans to update the server to incorporate Workspaces. I have assured the team that you are about to release an update for the R package. Can you please provide some info on this scheduled release? We are even willing to pilot a beta rollout and would greatly appreciate it.

Kind regards,
Burt Collymore

> Begin forwarded message:
> 
> From: Burt Collymore ***@***.***>
> Subject: Re: [michael-cw/SurveySolutionsAPI] Updated R package (Issue #7)
> Date: January 26, 2022 at 2:01:16 PM AST
> To: michael-cw/SurveySolutionsAPI ***@***.***>
> Cc: michael-cw/SurveySolutionsAPI ***@***.***>, Author ***@***.***>
> 
> Hi Michael,
> Thank you so much. This is wonderful news. Yes, trust me, I have been struggling with using other API packages and I am truly appreciative of how intuitive, robust, and complete your R package is, the data export feature is amazing,  I was up and running in no time. Thanks for this amazing tool. Yes, I too had a lot of difficulty with graphql, I never got it to work in the .net package and I’m still researching it, so I feel you there. Anyway, I’m wishing you all the best as I eagerly anticipate the updated release. Here is a link to what your innovation has made possible. Truly appreciated.
> 
> https://1drv.ms/v/s!AvlHmpjY7vUQiL8f0gd2Xaoj2EPkRw?e=YEJH4L <https://1drv.ms/v/s!AvlHmpjY7vUQiL8f0gd2Xaoj2EPkRw?e=YEJH4L>
> 
> Kind regards,
> Burt Collymore
>

**Comment by michael-cw** [comment]
update to workspaces completed. There will be some updates to the documentation over the next weeks. in case any new bug is detected, kindly open a new issues. Thanks for your patience, and good luck with the census.

**Comment by BECollymore** [comment]
Thak you so much Mr. Wild. And sorry if my superiors seemed a bit impatient. You have made available an exceptional R package. Truly appreciated.

Kind regards,
Burt
