### ISSUE TITLE
Thanks for publishing updated package!!!

### ISSUE THREAD

**Issue by BECollymore** [michael-cw/SurveySolutionsAPI#8]
Hi Michael,

Thanks for publishing the new updates. Truly appreciated.

Kind regards.

**Comment by BECollymore** [comment]
R version 4.1.2

**Comment by michael-cw** [comment]
Hi Burt,

Strange. I have installed it on three different machines, and it worked. Could you please run sessionInfo()?

Thanks.

Best

Michael

From: Burt Collymore ***@***.***>
Sent: Tuesday, March 1, 2022 7:40 PM
To: michael-cw/SurveySolutionsAPI ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [michael-cw/SurveySolutionsAPI] Error installing updated package (Issue #8)

[External]

Hi Michael,

Thanks for publishing the new update. I am getting the following error during installation:
devtools::install_github("michael-cw/SurveySolutionsAPI")
Error: Failed to install 'unknown package' from GitHub:
Timeout was reached: [api.github.com] Connection timed out after 10000 milliseconds

Can you please assist.

Thanks

-

**Comment by michael-cw** [comment]
I had an additional look on the problem, and found this here. Did you check if you can reach github from your R installation?

https://community.rstudio.com/t/remotes-package/103229/2

hope it works.

**Comment by BECollymore** [comment]
Hi Michael,
Thanks for responding... Everything is working nicely. Thanks. I will continue to incorporate the changes.

Kind regards,
Burt

**Comment by BECollymore** [comment]
Yes, it was a proxy issue. I tried installing the updates from the office network, hence the error. Everything works perfectly so far. Thanks

**Comment by michael-cw** [comment]
Glad to hear and you are welcome.



________________________________

**Comment by BECollymore** [comment]
Hi Michael,
Just one observation, but before I do so I must admit that due to time constraints/other engagements, I have not adequately revised the new updates to the R package. I am wondering( and correct me if I’m wrong) why you did not create one centralized point to set the workspaces (i.e. via the suso_set_key
Function), that way users would have less adjustments to make to their existing code.  Based on my brief observations, users now have to include the workspace in every function call. Kindly, inform me of any workarounds or will this be a future addition to the package.

Regards,
Burt

**Comment by ashwinikalantri** [comment]
I agree. Adding `suso_workspace` argument in the `suso_set_key` function and calling this with `suso_get_api_key("susoWorkspace")` would make the workflow quite easy. I doubt if there will be scenarios where someone will work in different workspaces within the same script. Even if that is the case, the arguments set in `suso_set_key` can be over-written by specifying the specific workspace in the function.

**Comment by BECollymore** [comment]
Yes. Thanks. I’m glad you see it this way. Ideally, this is what would have been expected of an update to any package, i.e the consideration for legacy code and applications.  Just think that it would have been so much simpler using this best practice. Unfortunately, we have a use-case scenario where there will be a multiplicity of workspaces, so you can imagine the complexity involved…I would just like to signal this to my team at the CSO…At this point and not without great effort and a little prayer, as is, the updates to the Survey Solutions R package is making maintenance of our Monitoring Application extremely complex. Hope that there can be some improvements.

Kind regards,
Burt
